# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

chef_cookbook_path: /vccw/provision
hostname: tsumugi.local
ip: 192.168.33.13
sync_folder: 'www/wordpress'
lang: ja
title: tsumugi
multisite: true
plugins:
  - dynamic-hostname
  - wp-total-hacks
  - tinymce-templates
  - theme-check
  - wordpress-importer
theme: 'tsumugi'
options:
  blogdescription: Weave your words eternally.
theme_unit_test: true
theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml
linked_clone: true
